### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by absemetov** [ramybenaroya/ember-cli-lightbox#8]
Hello!
When run: ember g ember-cli-lightbox
````
Unexpected identifier
SyntaxError: Unexpected identifier
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Function.Blueprint.load (/home/ubuntu/workspace/rzk-ember/node_modules/ember-cli/lib/models/blueprint.js:1276:29)
    at Function.Blueprint.lookup (/home/ubuntu/workspace/rzk-ember/node_modules/ember-cli/lib/models/blueprint.js:1253:24)
    at CoreObject.module.exports [as beforeRun] (/home/ubuntu/workspace/rzk-ember/node_modules/ember-cli/lib/utilities/merge-blueprint-options.js:24:27)

````

**Comment by ramybenaroya** [comment]
fixed in 1.0.2
